<?php
$translations = array(
		'add to timetrack'=>'Zur Zeiterfassung hinzufügen',
		'cancel'=>'abbrechen',
		'Child tasks'=>'Unteraufgaben',
		'complete'=>'abschließen',
		'Contacts'=>'Kontakte',
		'delete'=>'entfernen',
		'edit'=>'bearbeiten',
		'Files'=>'Dateien',
		'Invoices'=>'Rechnungen',
		'Log out ?'=>'? ausloggen',
		'open'=>'öffnen',
		'Parent'=>'übergeordnete Aufgabe',
		'Prerequisites'=>'Voraussetzungen',
		'Project'=>'Projekt',
		'Projects'=>'Projekte',
		'show closed child tasks'=>'abgeschlossene Unteraufgaben anzeigen',
		'start'=>'anfangen',
		'Task'=>'Aufgabe',
		'Tasks'=>'Aufgaben',
		'Timetrack'=>'Zeiterfassung',
		'Users'=>'Benutzer',
		'view'=>'ansehen',
		'wait'=>'abwarten',
);