<?php

$translations = array(
		'add model'=>'Modell hinzufügen',
		'Add model to project:'=>'Modellzu Projekt hinzufügen:',
		'Bookmarks' => 'Lesezeichen',
		'Company'=>'Firma',
		'Contacts'=>'Kontakte',
		'Description'=>'Beschreibung',
		'Documents'=>'Dokumente',
		'edit'=>'bearbeiten',
		'Files'=>'Dateien',
		'Invoices'=>'Rechnungen',
		'Items'=>'Artikel',
		'Log out ?'=>'? ausloggen',
		'Model'=>'Modell',
		'Models' => 'Modelle',
		'Notes'=>'Notizen',
		'Project'=>'Projekt',
		'Project: ?'=>'Projekt: ?',
		'Projects'=>'Projekte',
		'Tasks'=>'Aufgaben',
		'Timetrack'=>'Zeiterfassung',
		'Users'=>'Benutzer',
		'Y-m-d H:i:s'=>'d.m.Y H:i:s',
);
