<?php

$translations = array(
		'Add entry to items of ?'=>'Eintrag zu den Artikeln von ? hinzufügen',
		'Bookmarks' => 'Lesezeichen',
		'Company'=>'Firma',
		'Contacts'=>'Kontakte',
		'Description'=>'Beschreibung',
		'Documents'=>'Dokumente',
		'Edit item of ?'=>'Item von ? bearbeiten',
		'Files'=>'Dateien',
		'Invoices'=>'Rechnungen',
		'Items'=>'Artikel',
		'Item code'=>'Artikel-Code',
		'Item name'=>'Artikelname',
		'Items of ?'=>'Artikel von ?',
		'Log out ?'=>'? ausloggen',
		'Notes'=>'Notizen',
		'Price per unit'=>'Preis pro Einheit',
		'Save'=>'Speichern',
		'Select a company'=>'Firma auswählen',
		'Tags'=>'Stichworte',
		'Tasks'=>'Aufgaben',
		'Tax'=>'Steuersatz',
		'Timetrack'=>'Zeiterfassung',
		'Umbrella Item Management'=>'Umbrella Artikelverwaltung',
		'Unit'=>'Einheit',
		'Users'=>'Benutzer',
);
