<?php
$translations = array(
		'Actions' => 'Aktionen',
		'Add Task "?" to Timetrack'=>'Aufgabe "?" zu Zeiterfassung hinzufügen',
		'Bookmarks'=>'Lesezeichen',
		'Company'=>'Firma',
		'completed'=>'abgeschlossen',
		'Contacts'=>'Kontakte',
		'Description'=>'Beschreibung',
		'Edit Time'=>'Zeit bearbeiten',
		'End'=>'Ende',
		'Files'=>'Dateien',
		'Hours'=>'Stunden',
		'? hours'=>'? Stunden',
		'Invoices'=>'Rechnungen',
		'Log out ?'=>'? ausloggen',
		'new time'=>'neue Zeit',
		'No open time track existing!'=>'Es läuft keine Zeiterfassung!',
		'open'=>'offen',
		'Open timetracks'=>'laufende Zeiterfassungen',
		'pending'=>'wartend',
		'Projects'=>'Projekte',
		'== Select a timetrack =='=>'== Timetrack auswählen ==',
		'start' => 'Zeiterfassunng starten',
		'Start'=>'Beginn',
		'started'=>'gestartet',
		'State'=>'Status',
		'Subject'=>'Betreff',
		'Tasks'=>'Aufgaben',
		'Time'=>'Zeit',
		'Timetrack'=>'Zeiterfassung',
		'Users'=>'Benutzer',
);
