#!/bin/bash

cd $(dirname $0) # cd to directory in which script resides
SCRIPT_DIR=$(pwd)
DIRS=". user"
BASE=$(dirname $SCRIPT_DIR)

if [ -d ../user/db ]; then
	echo this should not be run in a live environment!
	exit -1
fi
service apache2 restart
for DIR in $DIRS; do
        echo looking for test_scripts in $BASE/$DIR/tests
	cd $BASE/$DIR/tests
	for SCRIPT in *test.py; do
		echo launching $SCRIPT
		python $SCRIPT || exit -1
	done
done
echo all tests passed.
exit 0

