#!/bin/bash

cd $(dirname $0) # cd to directory in which script resides
SCRIPT_DIR=$(pwd) 
DIRS=". user project task" # directories in which to look for tests
BASE=$(dirname $SCRIPT_DIR)

if [ -d ../user/db ]; then
	echo this should not be run in a live environment!
	exit -1
fi

service apache2 restart 2>/dev/null # start webserver

for DIR in $DIRS; do
	echo
	echo looking for test_scripts in $BASE/$DIR/tests
	cd $BASE/$DIR/tests
	
	for SCRIPT in *test.py; do
		# if FILTER is set, only start scripts whose name contains the respective text
		if [[ $SCRIPT == *$FILTER* ]]; then
			echo -n launching $DIR/tests/$SCRIPT
			python "$SCRIPT" || exit -1
		fi
	done
done
echo all tests passed.
exit 0

