<?php

$translations = array(
		'Address'=>'Adresse',
		'BDAY'=>'Geburtstag',
		'Bookmarks'=>'Lesezeichen',
		'City'=>'Ort',
		'Contacts'=>'Kontakte',
		'Country'=>'Land',
		'Edit Contact'=>'Kontakt bearbeiten',
		'EMAIL'=>'Email',
		'Files'=>'Dateien',
		'FN'=>'formatierter Name',
		'First Name'=>'Vorame',
		'Invoices'=>'Rechnungen',
		'Last Name'=>'Nachname',
		'Log out ?'=>'? ausloggen',
		'ORG'=>'Organisation',
		'Post Code'=>'Postleitzahl',
		'Projects'=>'Projekte',
		'Street'=>'Straße/Nummer',
		'Tasks'=>'Aufgaben',
		'TEL'=>'Telefon',
		'Timetrack'=>'Zeiterfassung',
		'Users'=>'Benutzer',
		'X-BANK-ACCOUNT'=>'Bankverbindung',
		'X-CUSTOMER-NUMBER'=>'Kundennummer',
		'X-COURT'=>'Amtsgericht',
		'X-TAX-NUMBER'=>'Steuernummer',
);
