<?php
$translations = array(
	'Actions'=>'Aktionen',
	'Assigned logins'=>'Verknüpfte Konten',
	'Bookmarks'=>'Lese&shy;zeichen',
	'Company'=>'Firma',
	'Contacts'=>'Kontakte',
	'Delete assignment'=>'Kontoverbindung löschen',
	'Files'=>'Dateien',
	'Invoices'=>'Rechnungen',
	'Login using email and password'=>'Mit Email und Passwort einloggen',
	'Login using OAuth 2 / OpenID Connect'=>'Mit OAuth 2 / OpenID Connect einloggen',
	'Log in using ? account.'=>'Mit ?-Account einloggen',
	'Log out ?'=>'? ausloggen',
	'Password'=>'Passwort',
	'Projects'=>'Projekte',
	'Sending post data to "?" :'=>'Sende POST-Daten an "?" :',
	'Sending data to: "?"'=>'Sende Daten an "?".',
	'Service name'=>'Service-Name',
	'Tasks'=>'Aufgaben',
	'Timetrack'=>'Zeiterfassung',
	'The default username/password is admin/admin.'=>'Standard-Nutzername/-Passwort ist admin/admin.',
	'User id'=>'Benutzer&shy;kennung',
	'Users'=>'Benutzer'
);
